version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lightSeek"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-unzywirrz2nz"
s3_prefix = "lightSeek"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
profile = "default"
